name: Runtime Issue
description: A crash is happening while your application is running
labels: [ bug ]
body:
  - type: input
    attributes:
      label: SQLDelight Version
    validations:
      required: true
  - type: input
    attributes:
      label: Application Operating System
      placeholder: Android, iOS, JVM, Native
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Stacktrace
      description: If possible, provide a stacktrace depicting the bug.
      render: shell
